### ISSUE TITLE
Fail to read user details for a given Github's user_id

### ISSUE THREAD

**Issue by nicolas2bert** [go-auth0/auth0#101]
**What happened**:

I get the following error when I try to read user details for a given Github's user_id:

`cannot unmarshal number into Go struct field UserIdentity.identities.user_id of type string.`

**Steps to reproduce**

```
api, err := management.New(auth0Issuer, auth0ClientID, auth0ClientSecret)
if err != nil {
     ...
}
u, err := api.User.Read(githubUserID)
```

`GET    /api/v2/users/{github_user_id}` returns JSON-encoded data.
`identities.user_id` is a JSON  **number** value  and has a [string](https://github.com/go-auth0/auth0/blob/v3.3.0/management/user.go#L87) target type.

**Comment by alexkappa** [comment]
Hi Nicolas, it is a known issue indeed and I'm trying to reach Auth0 for advise. Other SDKs (e.g. Java) use a generic type for options but I'm still unsure if I want to take that approach here (it leaves a lot more to users of this SDK).

There are some PRs and issues already filed, and we're working on a fix for this.

**Comment by alexkappa** [comment]
@nicolas2bert this issue has been addressed in the recent releases. Numeric IDs (e.g. GitHub) should be unmarshaled into a Go string correctly.

**Comment by nicolas2bert** [comment]
Great news, thank you :)
