### ISSUE TITLE
Why Client.Create doesn't return the ID of the created client?

### ISSUE THREAD

**Issue by AdallomRoy** [go-auth0/auth0#105]
Seems like it is returned from the API:
https://auth0.com/docs/api/management/v2#!/Clients/post_clients

Currently when you create a new client you need to search for it afterwards if you want to get its id...

**Comment by alexkappa** [comment]
Please take a look at the examples. The client is passed by reference and generated fields become available upon creation.

https://godoc.org/gopkg.in/auth0.v3/management#example-ClientManager-Create
