### ISSUE TITLE
Timeout issue or missing retry?

### ISSUE THREAD

**Issue by xiaotian-tan** [go-auth0/auth0#119]
Tried to use management client in my handler, but got this error below: 

failed to get management client for auth0. error: Post https://pmitc.auth0.com/oauth/token: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

It doesn't seem to be timeout issue to me, as it's not taking over 1 minute to finish the request. 

It'd be good that it can provide retry functionality to make it stable.

**Comment by alexkappa** [comment]
Hi @xiaotian-tan have you figured out a way to solve your issue? It seems to be a connectivity problem. Perhaps this could be a firewall blocking your connection?

I will close this, but feel free to re-open if I can be of help. Please include more detailed logs so I can be able to help you (i.e. use the `WithDebug(true)` option with `New`.
