### ISSUE TITLE
Change Tenant SessionLifetime and IdleSessionLifetime to float64

### ISSUE THREAD

**Issue by alexkappa** [go-auth0/auth0#127]
Change data type of `Tenant` `SessionLifetime` and `IdleSessionLifetime` to `float64`.

It seems that the Auth0 API allows saving fractions of an hour in these fields causing the marshaling/unmarshaling to fail when such values are presented.

```diff
type Tenant struct {
 
        // Login session lifetime, how long the session will stay valid (unit:
        // hours).
-       SessionLifetime *int `json:"session_lifetime,omitempty"`
+       SessionLifetime *float64 `json:"session_lifetime,omitempty"`
 
        // Force a user to login after they have been inactive for the specified number (unit: hours)
-       IdleSessionLifetime *int `json:"idle_session_lifetime,omitempty"`
+       IdleSessionLifetime *float64 `json:"idle_session_lifetime,omitempty"`
```

See: https://github.com/alexkappa/terraform-provider-auth0/issues/233

**Comment by bergbrains** [comment]
@alexkappa, what's the path forward for implementing this change?  We are very interested in moving this forward.
