### ISSUE TITLE
User struct missing last_ip and logins_count fields

### ISSUE THREAD

**Issue by ernestoalejo** [go-auth0/auth0#136]
The [User struct](https://github.com/go-auth0/auth0/blob/master/management/user.go#L13) is missing two fields we are going to read from the API responses: `last_ip` and `logins_count`

I will follow this issue with a PR shortly.

**Comment by alexkappa** [comment]
Hi @ernestoalejo, could you point to some documentation that describes these fields?

Thanks for the PR, it looks good!

**Comment by ernestoalejo** [comment]
They are described in the official docs: https://auth0.com/docs/api/management/v2#!/Users/get_users

A screenshot of them:

![Screenshot from 2020-09-03 14-24-44](https://user-images.githubusercontent.com/961966/92114536-46dcd400-edf1-11ea-9bf4-972ee932ab4e.png)

I added `Read only, cannot be modified.` to the Go comments to avoid issues with people trying to fill the fields when creating a new user, but I can remove the annotation if needed.

**Comment by alexkappa** [comment]
Thanks @ernestoalejo I've merged the PR in. Will cut a new release soon.
