### ISSUE TITLE
Cannot clear fields in PATCH request

### ISSUE THREAD

**Issue by sebastian-stephan** [go-auth0/auth0#148]
This is also related to https://github.com/go-auth0/auth0/issues/74.

The resource structs use pointers, which will never be marshalled when set to `nil` due to the `omitempty` tag. However sometimes that would be required in a PATCH request if you want to clear a field.

As an example the `given_name` field on a user with the [Patch User](https://auth0.com/docs/api/management/v2#!/Users/patch_users_by_id) request: Auth0 does not accept an empty string, and the correct way to clear this field would be to send `null` in the JSON payload.

I briefly looked for inspiration how this is solved in other SDKs, and found a similar bug in the GitHub SDK: https://github.com/google/go-github/issues/236 where the suggested solution is to manually create a request.

I guess to do this one could expose the underlying `*http.Client` with a getter or make the `request` function public. Then you could construct the payload manually:
```golang
payload := struct {
    GivenName *string `json:"given_name"`
}{}
```
Not sure what the other options would be. I guess one could always replace all pointers with some custom type?

**Comment by alexkappa** [comment]
Hi @sebastian-stephan, with the changes made in #151 it is now possible to gain access to the underlying client in order to make the request manually.

The `NewRequest`, `Do` and `Request` methods are probably what you're looking for. Also the `URI` method can help with specifying the right URL path.
