### ISSUE TITLE
Link a user account API

### ISSUE THREAD

**Issue by alejandro-delgado-garcia** [go-auth0/auth0#155]
Hi,

Is this API available in the client https://auth0.com/docs/api/management/v2#!/Users/post_identities ?

**Comment by alexkappa** [comment]
Hello @alejandro-delgado-garcia unfortunately not, but pull requests are welcome!

**Comment by jmaeso** [comment]
FYI: Trying my best here https://github.com/go-auth0/auth0/pull/178

**Comment by jmaeso** [comment]
Merged and published within the [v5.6.0 release](https://github.com/go-auth0/auth0/releases/tag/v5.6.0)
I think this issue can be closed @alexkappa :D
