### ISSUE TITLE
Universal Login Template

### ISSUE THREAD

**Issue by gagalago** [go-auth0/auth0#158]
[Universal login template](https://auth0.com/docs/universal-login/new-experience/universal-login-page-templates#page-templates-api) is missing from this SDK (see [anounce](https://support.auth0.com/notifications/5f526b537b9bed000bed935b))

I can try to work on that but do you have some inside on how to do it before I start?

**Comment by alexkappa** [comment]
Hi @gagalago, thank you for raising this issue. Feel free to give it a try, and let me know if you need any help.

**Comment by yvovandoorn** [comment]
Closing this issue as #161 was merged in last year.
