### ISSUE TITLE
Read error when signing in with Apple

### ISSUE THREAD

**Issue by saito-kosuke** [go-auth0/auth0#171]
After I sign in with Apple, the error below has occurred when executing the read method https://github.com/go-auth0/auth0/blob/master/management/user.go#L200. 
json: cannot unmarshal string into Go struct field User.email_verified of type bool
Could you tell me how to prevent this problem?

**Comment by saito-kosuke** [comment]
@alexkappa
The json response from Apple is “email_verified”:“true” but that from other connections is “email_verified”:true
So I think you should convert boolean from string "true".
Thank you for your kindness.

**Comment by alexkappa** [comment]
Hi @saito-kosuke, this issue has been addressed in #181. Feel free to give it a try using the latest release. Thanks for your patience!
