### ISSUE TITLE
Add support for additional client refresh_token fields

### ISSUE THREAD

**Issue by woz5999** [go-auth0/auth0#182]
https://auth0.com/docs/api/management/v2#!/Clients/post_clients

The api fields 
```
infinite_token_lifetime
idle_token_lifetime
infinite_idle_token_lifetime
```
 are not currently supported in the sdk.

**Comment by alexkappa** [comment]
@woz5999 this one seems to be a duplicate of #184. Shall we close it?

**Comment by woz5999** [comment]
@alexkappa i'll close it. i must've double clicked or something and submitted the issue twice
