### ISSUE TITLE
ConnectionManager.ReadByName() method returns a connection when name field is empty 

### ISSUE THREAD

**Issue by zzbennett** [go-auth0/auth0#185]
### Package Version

```
v5.6.0
```

### Affected Resources

* `management.ConnectionManager`

### Sample Code

```go
// Copy-paste your Go code here - for large snippets, please consider using a [Github Gist](https://gist.github.com/) instead.
auth0MgmtClient.Connection.ReadByName("")
```

### Expected Behavior

Respond with error or nil.

### Actual Behavior

It responds with a connection, looks like the first connection in the tenant when listing all connections.

### Output

```go
// Copy-paste the output here - for long outputs, please consider using a [Github Gist](https://gist.github.com/) instead.
```

### References

* #0000

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by alexkappa** [comment]
Hi @zzbennett, thank you for reporting this. It definitely looks like a bug.

The implementation of `ReadByName` internally uses `List` and takes the first connection from the returned list.

```go
// ReadByName retrieves a connection by its name. This is a helper method when a
// connection id is not readily available.
func (m *ConnectionManager) ReadByName(name string, opts ...RequestOption) (*Connection, error) {
	c, err := m.List(append(opts, Parameter("name", name))...)
	if err != nil {
		return nil, err
	}
	if len(c.Connections) > 0 {
		return c.Connections[0], nil
	}
	return nil, &managementError{404, "Not Found", "Connection not found"}
}
```

Perhaps we can check the value `name` and  return an error if it's is empty. Are you open to submitting a PR?

**Comment by zzbennett** [comment]
yea sure I can take a stab
