### ISSUE TITLE
403 Forbidden: Insufficient scope, expected any of: create:user_tickets

### ISSUE THREAD

**Issue by hyprnick** [go-auth0/auth0#195]
I'm trying to use the Management API to create a change password ticket and I'm getting the following error:  

```
403 Forbidden: Insufficient scope, expected any of: create:user_tickets
```

I'm not sure if I have an issue with my application setup or my code setup.  

This document (https://auth0.com/docs/tokens/management-api-access-tokens/get-management-api-access-tokens-for-production), says to specify a `grant_type` however I cannot find this option in this package.  

Am I on the right track here?  How can I accomplish this? 

Thank you

**Comment by yvovandoorn** [comment]
Hi @hyprnick this sounds more like the M2M application authorized against Auth0's Management API doesn't have the `create:user_tickets` scope enabled. 

This can be done via the Dashboard interface and would look something like:
<img width="495" alt="Screen_Shot_2021-03-23_at_20_36_16" src="https://user-images.githubusercontent.com/2694655/112207735-c8724300-8c17-11eb-9f2a-ffd28d2c21c7.png">
