### ISSUE TITLE
Can't update user email

### ISSUE THREAD

**Issue by munir131** [go-auth0/auth0#217]
### Description

As per REST api doc 
If you are updating email or phone_number you can specify, optionally, the client_id property.
But in this sdk user struct doesn't have client_id support.

### Package Version

```
v5
```

### Affected Resources

* `management.User`

### Expected Behavior

Email should be updated

### Actual Behavior

no user with the provided email found

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by sergiught** [comment]
Closed and cloned this issue to https://github.com/auth0/go-auth0/issues/16
