### ISSUE TITLE
Docs links in README are invalid

### ISSUE THREAD

**Issue by mitar** [go-auth0/auth0#223]
E.g., `https://docs.auth0.com/link-accounts`.

**Comment by alexkappa** [comment]
Hi @mitar, there are a number of links in the readme. Please be more specific in your request and I can look into it.

**Comment by mitar** [comment]
I literally posted an example of not working link above. Have you tried searching for it in documentation? So `https://docs.auth0.com/link-accounts`.

**Comment by mitar** [comment]
So all which point to `docs.auth0.com`? See [few examples here](https://github.com/go-auth0/auth0/blob/67ed4ed49fbc0e6f71d6664d61d6c43151588382/README.md?plain=1#L99-L104).
