### ISSUE TITLE
WebAuthn Roaming and Platform support

### ISSUE THREAD

**Issue by JayHelton** [go-auth0/auth0#224]
### Description

Hello! With the release of Webauthn, it would be nice to add support in this lib for the factor settings.
I would love to work on it, and will actual start at the time of creating this issue.
### Affected Resources

* `management.GuardianManager`

### References
https://auth0.com/docs/mfa/webauthn-as-mfa

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by sergiughf** [comment]
Hey @JayHelton thanks for opening this issue, apologies that it took a while to reply back over here as well. It seems that we already added support for webauthn through https://github.com/go-auth0/auth0/pull/225 (thanks a lot for that contribution ⭐ )  and as such we'll be closing this issue down. In case of need please feel free to reopen.
