### ISSUE TITLE
Recommended to use interface instead of struct in xxxManager

### ISSUE THREAD

**Issue by starsz** [go-auth0/auth0#226]
### Description

Hello, I found that the xxxManager was defined as a struct.
And it was referenced in management.

https://github.com/go-auth0/auth0/blob/0ed82d242c8bfacb02db3352ef6688591108b371/management/management.go#L85-L106

https://github.com/go-auth0/auth0/blob/0ed82d242c8bfacb02db3352ef6688591108b371/management/user.go#L280-L282

### Affected Resources

* `management.Xxx`
* `management.XxxManager`

### Potential Sample Code

I recommend to use interface instead of struct in xxxManager
Like this:

```Go
type UserManager interface{
 Create(u *User, opts ...RequestOption) error
 Read(id string, opts ...RequestOption) (u *User, err error)
 Update(id string, u *User, opts ...RequestOption) (err error) 
 List(opts ...RequestOption) (ul *UserList, err error) 
...
}
```

So that we can mock the `Management.User` and do some unit tests.

The same as other managers.

**Comment by alexkappa** [comment]
Hi @starsz, I find the proposal to adopt interfaces reasonable and your use case valid. Its a large undertaking however and a potentially backwards incompatible change (so a major version bump may be warranted).

Just to make sure you have explored the option, did you try to pass your own implementation of `http.Client`? Its not exactly the same, but you can mock the HTTP layer by providing a custom client.

**Comment by emmaLP** [comment]
@alexkappa do you have an example where injecting a mock http client has been done for auth0?

**Comment by mutefiRe** [comment]
> Hi @starsz, I find the proposal to adopt interfaces reasonable and your use case valid. Its a large undertaking however and a potentially backwards incompatible change (so a major version bump may be warranted).
> 
> Just to make sure you have explored the option, did you try to pass your own implementation of `http.Client`? Its not exactly the same, but you can mock the HTTP layer by providing a custom client.

```
func WithClient(client *http.Client) ManagementOption {
	return func(m *Management) {
		m.http = client
	}
}
``` 
You can't pass an own implementation of `http.Client` either because the function uses the http.Client struct type instead of an interface around the `Do` method. Is there any other way to inject it?

**Comment by sergiught** [comment]
Closed and cloned this issue to https://github.com/auth0/go-auth0/issues/17
