### ISSUE TITLE
Please support custom text for a specific prompt and language

### ISSUE THREAD

**Issue by kiranms-newpage** [go-auth0/auth0#227]
### Description

Please support custom text for a specific prompt and language. The below two APIs
https://auth0.com/docs/api/management/v2#!/Prompts/get_custom_text_by_language
https://auth0.com/docs/api/management/v2#!/Prompts/put_custom_text_by_language

GET and PUT of /api/v2/prompts/{prompt}/custom-text/{language}

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by sergiughf** [comment]
Hey @kiranms-newpage, apologies for the late reply on this issue. Support for custom texts on prompts has been added through https://github.com/go-auth0/auth0/pull/240. As such we'll be closing this issue down, but please feel free to reopen in case of need.
