### ISSUE TITLE
Support `upstream_params` option for connections

### ISSUE THREAD

**Issue by choncou** [go-auth0/auth0#234]
### Description

Currently I don't see if it is possible to pass `upstream_params` in the options for a connection. My goal is for the functionality to be available in the terraform provider.

My use-case would be to be able to pass a through `"prompt":{"value":"select_account"}` to a google oauth2 connection, which will help avoid an issue of Google always using the current signed-in Google account, and not allowing a user to pick a different account

### Affected Resources

* `management.Connection`

### Potential Sample Code

N/A

### References

* https://auth0.com/docs/api/management/v2#!/Connections/patch_connections_by_id
* https://auth0.com/docs/connections/pass-parameters-to-idps#static-parameters

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by sergiught** [comment]
Closed and cloned this issue to https://github.com/auth0/go-auth0/issues/18
