### ISSUE TITLE
no examples

### ISSUE THREAD

**Issue by steven-varga** [go-auth0/auth0#239]
### Question
It looks like a great work! It could be even more attractive if there was a minimum working example provided. From the page I don't quite understand what is the relationship between listed types and the linked auth0 API calls.  In other words how to call 
[get_users_by_email](https://auth0.com/docs/api/management/v2/#!/Users_By_Email/get_users_by_email) function?

update:
I figured it out from the [source code](https://github.com/go-auth0/auth0/blob/c62432355c8d2ee5c7643e696fe8e9ce3ba061f8/management/management.go#L179)

**Comment by alexkappa** [comment]
Hi @steven-varga, have you looked into the [pkg.go.dev](https://pkg.go.dev/gopkg.in/auth0.v5@v5.21.0/management#pkg-examples) reference? it contains several examples including listing users. For more details the [UserManager](https://pkg.go.dev/gopkg.in/auth0.v5@v5.21.0/management#UserManager) section should cover you for anything related to users.
