### ISSUE TITLE
Breaking changes made in dot releases?

### ISSUE THREAD

**Issue by sethyates** [go-auth0/auth0#248]
### Question

This commit https://github.com/go-auth0/auth0/commit/a09cf1696a4a5a3abf23c82c0683749499225c3b is a breaking change and was released as a minor release (5.19 -> 5.20).

What is your release policy regarding breaking changes?

**Comment by alexkappa** [comment]
Hi @sethyates, indeed I broke the semver rules here. But since the changes were only somewhat obtrusive and actions are not widely adopted I avoided bumping a major version. 

In retrospect, I regret that. Apologies if this made upgrading a hassle.
