### ISSUE TITLE
Ticket missing field ClientId for ChangePassword and VerifyEmail

### ISSUE THREAD

**Issue by scampbell-zus** [go-auth0/auth0#253]
### Description

According to the Auth0 [documentation](https://auth0.com/docs/api/management/v2#!/Tickets/post_password_change), the endpoint to request a password change and verify email should be able to take an additional argument of ClientID

client_id: ID of the client. If provided for tenants using New Universal Login experience, the user will be prompted to redirect to the default login route of the corresponding application once the ticket is used. See Configuring Default Login Routes for more details.

Currently, this library does not support passing in this argument, and as such removes the option for being navigated to the correct login page.

### Affected Resources

* `management.Ticket`

### References

Documentation of Ticket endpoints:
https://auth0.com/docs/api/management/v2/#!/Tickets/post_email_verification
https://auth0.com/docs/api/management/v2/#!/Tickets/post_password_change

Similar GitHub issues within other language SDKs:
https://github.com/auth0/auth0-java/issues/351
https://github.com/auth0/auth0.net/issues/463 

* #0000

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by alexkappa** [comment]
Hi @scampbell-zus, thanks for reporting. The related issues are very helpful!

**Comment by sergiught** [comment]
Closed and cloned this issue to https://github.com/auth0/go-auth0/issues/21
