### ISSUE TITLE
Sdk itself handles request for Management Api Rate Limiting

### ISSUE THREAD

**Issue by sambhavjain9138** [go-auth0/auth0#261]
### Question
we are currently using this SDK to make management api calls. But we face some error due to management api rate limiting. Following is an article for the same. 
https://auth0.com/docs/troubleshoot/customer-support/operational-policies/rate-limit-policy/management-api-endpoint-rate-limits

During this request, auth0 returns a status code of 409, which helps us identify that the error is due to rate limiting. So can sdk itself make a small delay and then make a retry, during such responses? 

Even if it doesnt, How can we get this response status code in the response so as to make such check and introduce delay?

**Comment by sergiught** [comment]
Closed and cloned this issue to https://github.com/auth0/go-auth0/issues/23
