### ISSUE TITLE
Auth0 add roles to API v2

### ISSUE THREAD

**Issue by sinnedh** [go-auth0/auth0#35]
Auth0 has added their authorization model using roles and permissions to their API:
  https://auth0.com/docs/api/management/v2#!/Roles/get_roles
  https://auth0.com/docs/api/management/v2#!/Users/get_roles

I would really love to work on this but I'm new to golang and therefore would need a little assistance.

**Comment by alexkappa** [comment]
Hi @sinnedh,

It would be much appreciated and I'd be happy to help. I would say the way to go is to read the code and see how its done for other resources, and try to remain in a similar style.

You can start small and send a PR, I can help you with some feedback and we can take it from there.

Cheers,
Alex

**Comment by sinnedh** [comment]
Thanks @alexkappa !

I'm not able to run the tests ...

```
/go/src/auth0 # pwd
/go/src/auth0
/go/src/auth0 # ls
Gopkg.lock     Gopkg.toml     LICENSE        README.md      auth0.go       auth0_test.go  internal       management     wercker.yml
/go/src/auth0 # go test ./...
management/management.go:15:2: use of internal package gopkg.in/auth0.v1/internal/client not allowed
/go/src/auth0 #
```

Could you help me with that? I would document it afterwards in the README.

**Comment by alexkappa** [comment]
Hi @sinnedh, I suspect something to do with the `GOPATH`? Did you check out this package inside $GOPATH/src/gopkg.in/auth0.v1 ?

**Comment by alexkappa** [comment]
@sinnedh I had some time on my hands today and worked on roles in #37 . Would you like to use that as a reference and perhaps add the corresponding methods to the `Users` resource?

https://auth0.com/docs/api/management/v2#!/Users/get_roles
https://auth0.com/docs/api/management/v2#!/Users/delete_roles
https://auth0.com/docs/api/management/v2#!/Users/post_roles

Best,
Alex

**Comment by sinnedh** [comment]
> @sinnedh I had some time on my hands today and worked on roles in #37 . Would you like to use that as a reference and perhaps add the corresponding methods to the `Users` resource?
> 
> https://auth0.com/docs/api/management/v2#!/Users/get_roles
> https://auth0.com/docs/api/management/v2#!/Users/delete_roles
> https://auth0.com/docs/api/management/v2#!/Users/post_roles
> 
> Best,
> Alex

@alexkappa Sure! I will try this over the weekend.

Cheers, Dennis

**Comment by sinnedh** [comment]
@alexkappa I have created a PR on this https://github.com/go-auth0/auth0/pull/38 that is based on the branch that you have started.
