### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by SimonBarendse** [go-auth0/auth0#39]
Hi @alexkappa,

on creation of a user, we'd like to handle different types of returned errors differently. For example, an error for an email address that is already in use would be handled differently than an error for a too weak password.

Example:
```
err := m.User.Create(user)
if IsErrEmailAlreadyExists(err) {
  // handle
}
if IsErrPasswordTooWeak(err) {
  // handle
}
...
```

How would you feel about adding these error check functions? Do you have other suggestions?

I'm happy to take a crack at it once we have decided what way to go with this.

**Comment by alexkappa** [comment]
Hi @SimonBarendse, you could use the http status codes to distinguish these particular cases. An email address that is already in use would produce a 409 error which you can test using the `Status()` method.

```Go
if err := api.User.Create(u); err != nil {
    if err.(management.Error).Status() == http.StatusConflict {
        // handle email already exists
    }
}
```

I'm a bit reluctant to create methods to check the kind of errors from parsing error messages as it might be subject to subtle changes in the API.

Best,
Alex

**Comment by SimonBarendse** [comment]
@alexkappa I don't think we can do without checking the messages in all cases. For example, the username already exists and the password too weak error both return an `http.StatusBadRequest`.

Consumers of the package could check the error message using `error.Error()`. Can we consider [`managementError.Error()`](https://github.com/go-auth0/auth0/blob/v1.1.1/management/management.go#L236) stable?

Alternatively, we could add the helper functions to save others from having to implement and maintain the same error checking.

**Comment by alexkappa** [comment]
Hi @SimonBarendse, `management.Error()` can be considered stable. As you can see there is no special handling with regards to the kind of error from `managementError`. 

As long as Auth0 doesn't change their messaging, it can be relied upon, but its in your responsibility then if you want to build logic on top of that. I can't commit to maintaining helper functions as I see that potentially it will become a pain to maintain such functionality. 

You see, if we support this for users, why not for all other resources? Thats something no other SDK supports as far as I can tell, possibly for the same rationale.

To entertain the possibility, I got as far as this [gist](https://gist.github.com/alexkappa/807d13e6cd6f5ac713d2918818e0df3b), but the overhead of maintaining the numerous errors that may occur (and tracking their changes) deter me from pursuing it.

**Comment by SimonBarendse** [comment]
Hi @alexkappa, I can see how this could quickly grow to big to maintain. I'll close this issue and use `management.Error()` upstream. Thanks!

**Comment by mackenbach** [comment]
> For example, the username already exists and the password too weak error both return an `http.StatusBadRequest`.

In principle I agree with @alexkappa that if possible the matching should be done on HTTP status codes. That's what they're meant for. Relying on matching the exact error message is very fragile. If someone were to e.g. fix a typo in an error message, the code relying on the matching logic would break. 

To solve this particular issue, it may be as simple as changing the status code returned by Auth0 to `http.StatusConflict` for the `username already exists` error. I would expect this type of error to return a `409` status code anyway, not a `400`.

On a more general level, I've done a bit of research on the topic of error handling and it seems there are a few avenues for possible solutions:

- You can have one common error type and use an error code system to distinguish between different specific errors. You see this a lot in the golang database drivers, e.g. `pq`: https://github.com/lib/pq/blob/master/error.go Now, this is no walk in the park but it's somewhere in the middle in terms of code user burden `err.(management.Error).Code() == management.ErrorCodeUserAlreadyExists` vs. required effort to build.
- You can implement a handful of check functions to help with the matching logic for common error types, e.g. `management.IsUserAlreadyExists(err error)`. You see this quite often in the wild for e.g. `os.IsNotExist(err)`
- Finally, it should be noted that these sentinel errors should be avoided as much as possible. They become part of the public API of the `management` package. Dave Cheney wrote a great blog post on this: https://dave.cheney.net/2016/04/27/dont-just-check-errors-handle-them-gracefully

I think there's a balance to find between implementing a flexible matching system for certain errors that do trigger different behavior for users without encouraging over use of sentinel errors and creating a maintenance burden.
