### ISSUE TITLE
Support for Go 1.11?

### ISSUE THREAD

**Issue by mzmousa** [go-auth0/auth0#47]
Is there any way to make this backwards compatible with Go 1.11?

**Comment by alexkappa** [comment]
What do you mean @mzmousa? Are you referring to modules?

**Comment by mzmousa** [comment]
Yes - maybe a Go newbie question, but I have a project running go 1.11 and I want to use this library. What would be a proper way to override https://github.com/go-auth0/auth0/blob/master/go.mod#L3 in my project?

**Comment by SimonBarendse** [comment]
The [Go 1.12 release notes](https://golang.org/doc/go1.12#modules) state the following about this:

> The go directive in a go.mod file now indicates the version of the language used by the files within that module. It will be set to the current release (go 1.12) if no existing version is present. If the go directive for a module specifies a version newer than the toolchain in use, the go command will attempt to build the packages regardless, and will note the mismatch only if that build fails.
>
> This changed use of the go directive means that if you use Go 1.12 to build a module, thus recording go 1.12 in the go.mod file, you will get an error when attempting to build the same module with Go 1.11 through Go 1.11.3. Go 1.11.4 or later will work fine, as will releases older than Go 1.11. If you must use Go 1.11 through 1.11.3, you can avoid the problem by setting the language version to 1.11, using the Go 1.12 go tool, via go mod edit -go=1.11.

So upgrading to go `1.11.4` should fix your build.

---

As the project does build with go `1.11`, we could consider updating the required module in the `go.mod` to support Go `1.11` through `1.11.3`. If we do, I think we should update the CI (wercker) to run on `golang:1.11` as well, next to running the latest release.

I don't think this is necessary for now.

**Comment by alexkappa** [comment]
Is this issue still relevant?
