### ISSUE TITLE
User model does not have "picture" field

### ISSUE THREAD

**Issue by startnow65** [go-auth0/auth0#49]
[Auth0 API](https://auth0.com/docs/api/management/v2#!/Users/get_users) returns the url to the profile picture of a user as part of the fields retured for a user.

The `management.User` model however does not have the `picture` field and therefore not extracting this value from the response.

**Comment by rstefan1** [comment]
Solved in https://github.com/go-auth0/auth0/commit/ab9d0b6002627acabb22987575aa160023d48f49
