### ISSUE TITLE
Make all calls context aware

### ISSUE THREAD

**Issue by someone1** [go-auth0/auth0#78]
There is no way to pass a context to calls with the management client, so things like per-call tracing, timeouts, etc. are not possible. It is idiomatic in Go to utilize context.Context for non-trivial code paths such as those performing an RPC request.

**Comment by alexkappa** [comment]
You are absolutely right, in retrospect I wish I have started with that from the get go. If time permits I'll give it a go. Meanwhile, lets keep this ticket open for discussion.

Thanks!

**Comment by alexkappa** [comment]
All calls are now context aware since #151 was merged.
