### ISSUE TITLE
ResourceServer.options is unused

### ISSUE THREAD

**Issue by maroux** [go-auth0/auth0#80]
Should probably remove?

**Comment by alexkappa** [comment]
Thanks for submitting @maroux,

For reference, the field in question is [this](https://github.com/go-auth0/auth0/blob/master/management/resource_server.go#L43). The [docs](https://auth0.com/docs/api/management/v2#!/Resource_Servers/post_resource_servers) don't seem to reference the field and its likely removed by Auth0.

**Comment by sergiught** [comment]
Closed and cloned this issue to https://github.com/auth0/go-auth0/issues/13
