### ISSUE TITLE
Unable to find ClientId of created client

### ISSUE THREAD

**Issue by dan-j** [go-auth0/auth0#88]
The API signature to create a client is as follows:

```go
func (cm *ClientManager) Create(c *Client) (err error)
```

If a user sets `c.ClientID` to a desirable value, you get a 403 Forbidden with a message: ` This operation must be authorized by Auth0`.

If a user doesn't set `c.ClientID`, the request succeeds but then there's no way to retrieve the new `ClientID` because the method call just returns `nil`.

A quick look suggests all POST requests have the same issue? Is there willingness to change this behavior, it would be a big breaking change, but pretty much renders this SDK useless to me

**Comment by alexkappa** [comment]
@dan-j, the client you create is passed _by reference_. You can inspect its value after the method has completed.

**Comment by dan-j** [comment]
Ohhhhhhhh, well that's embarrassing that I hadn't noticed this, I'm creating my client inline like so:

```go
return manager.Create(&management.Client{
		...
})
```

Thanks for the quick response!
