### ISSUE TITLE
Support page_background gradient for Branding

### ISSUE THREAD

**Issue by apricote** [go-auth0/auth0#94]
Endpoint: https://auth0.com/docs/api/management/v2#!/Branding/patch_branding

Currently only the string syntax for `colors.page_background` is supported. It would be great, if you could also support the Color Gradient object syntax.

Currently supported syntax:

```json5
{
  "colors": {
    "page_background": "#f9f9f9", // <- Only hex string
    "primary": "#e74c3c"
  },
  "favicon_url": "https://example.com/favicon.ico",
  "logo_url": "https://example.com/logo.png"
}
```

Color Gradient Syntax:

```json5
{
  "colors": {
    "page_background": { // Full object to describe color gradient
      "type": "linear-gradient",
      "start": "#f3c2bd",
      "end": "#e74c3c",
      "angle_deg": 35
    },
    "primary": "#e74c3c"
  },
  "favicon_url": "https://example.com/favicon.ico",
  "logo_url": "https://example.com/logo.png"
}
```

**Comment by alexkappa** [comment]
Hi @apricote, thanks for submitting this issue. To do this we would have to implement a type with a custom marshal/un-marshal.

Are you willing to give it a go?

**Comment by apricote** [comment]
I will give it a try.
